#!/usr/bin/env ruby

require "pathname"

def create_zip(files)
  system "trash", "tmp" if Pathname("tmp").exist?
  Pathname("tmp").mkpath
  files.each do |name, content|
    Pathname("tmp/#{name}").write(content)
  end
  Dir.chdir("tmp") do
    system "rar", "a", "output.rar", *files.keys
  end
  Pathname("tmp/output.rar").open("rb", &:read)
end

flag = ARGV[0] or raise
real = "The answer is #{flag} !"
real += "\n" * (4096 - real.size)
fake = "There is no answer here :-("
fake += "\n" * (4096 - fake.size)

expanded = 4096

16.times do |i|
  extname = i == 0 ? "txt" : "rar"
  real_files = (0..15).map{|i| "%x.#{extname}" % i}.zip(([real] + [fake] * 15).shuffle).to_h
  fake_files = (0..15).map{|i| "%x.#{extname}" % i}.zip([fake] * 16).to_h
  real = create_zip(real_files)
  fake = create_zip(fake_files)

  expanded *= 16
end

open("archive.rar", "wb") do |fh|
  fh.write real
end

puts "Expanded size: #{expanded}"
puts "Compressed size: #{real.size}"
puts "Ratio: #{expanded / real.size}"
